name: 🐛 버그 리포트 (팀용)
description: 팀 프로젝트에서 발견된 버그를 신고합니다
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: 심각도
      options:
        - 🔴 Critical - 서비스 중단/메인 기능 불가
        - 🟠 High - 주요 기능에 영향
        - 🟡 Medium - 일부 기능에 영향
        - 🟢 Low - 성능 저하
      default: 2
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: 발생 환경
      description: 어떤 환경에서 버그가 발생했나요?
      options:
        - 🧪 Staging (테스트 환경)
        - 💻 Development (로컬 개발 환경)
        - 📱 Mobile (브라우저)
      default: 2
    validations:
      required: true

  - type: input
    id: affected_feature
    attributes:
      label: 영향받는 기능
      description: 어떤 기능/모듈에서 버그가 발생했나요?
      placeholder: 예시) 사용자 인증, 팀 기능, 댓글 기능
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: 버그 설명
      description: 발생한 문제를 구체적으로 설명해주세요
    validations:
      required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: 재현 단계
      description: 버그를 재현하는 방법을 단계별로 설명해주세요
      placeholder: |
        1. 로그인 페이지로 이동
        2. 이메일 필드에 'test@example.com' 입력
        3. 비밀번호 필드는 비워둠
        4. 로그인 버튼 클릭
        5. 에러 발생 확인
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: 예상 동작
      description: 정상적으로 작동한다면 어떻게 되어야 하나요?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: 실제 동작
      description: 실제로는 어떻게 동작하나요?
    validations:
      required: true

  - type: textarea
    id: error_logs
    attributes:
      label: 에러 로그/콘솔 메시지
      description: 브라우저 콘솔이나 서버 로그의 에러 메시지를 첨부해주세요
      render: shell

  - type: input
    id: commit_hash
    attributes:
      label: 관련 커밋/브랜치
      description: 버그가 발생한 시점의 커밋 해시나 브랜치명
      placeholder: 예시) develop, feat/user-auth, a1b2c3d4

  - type: checkboxes
    id: impact_assessment
    attributes:
      label: 영향도 체크
      description: 이 버그가 미치는 영향을 체크해주세요
      options:
        - label: 데이터 손실 위험
        - label: 보안 이슈 가능성
        - label: 성능 저하 발생
        - label: 다른 기능에 연쇄 영향